### ISSUE TITLE
卖的比淘宝还贵,你还好意思卖

### ISSUE THREAD

**Issue by liruibingniubi** [yizhao2/test#2]

**Comment by liruibingniubi** [comment]
微信15533829110,找我买

**Comment by yizhao2** [comment]
自己没有账号不会发布吗？非要到人家这里找存在感，真有意思，淘宝月卡最低30你在这里叫什么？选择权在客户手里，人家觉得我的软件可以就买，我一没强买强卖二没骗人跑路，为什么不好意思？轮到你说话吗？你是个什么小丑？看到帖的注意了，找了第三方买被骗跑路的别来找我

**Comment by yizhao2** [comment]
![image](https://github.com/user-attachments/assets/c249a2b5-d91a-40a2-8483-78e9d58cba40)
成分复杂，跑个JS都跑不了你还能干啥？还找你买，取个名字叫自己牛逼的liruibingniubi，我的评价是李瑞冰傻逼
